U1 login navegation
wolox-training/ll-android pull request #3
Opened 2022-10-03 19:07 UTC by lauuta185

### Summary
In this card, i add a wolox link page in the app footer and I made the login and register buttons lead to a blank activity.
### Card
[[U1] Maquetado: Login - Navegación](https://trello.com/c/liUXWtu9/25-u1-maquetado-login-navegaci%C3%B3n)
### Review

2022-10-03 19:22 UTC, bdecorneliis requested changes
Some comment. 

_A good developer also delivers visually beautiful code..._
_-Me_

2022-10-03 19:22 UTC, bdecorneliis commented on app/src/main/java/com/example/wnews/LoginActivity.kt
> +        } else println("hola")
Bye 👀

2022-10-03 19:22 UTC, bdecorneliis commented on app/src/main/java/com/example/wnews/LoginActivity.kt
> +            openWebPage("https://www.wolox.com.ar")
Move the string values into string.xml!

2022-10-03 19:22 UTC, bdecorneliis commented on app/src/main/java/com/example/wnews/LoginActivity.kt
> +
Let's make your code more visually "elegant". Delete these unused lines...

2022-10-03 19:22 UTC, bdecorneliis commented on app/src/main/res/layout/fragment_home.xml
> +    <!-- TODO: Update blank fragment layout -->
Delete this commened line

2022-10-04 13:50 UTC, lauuta185 commented on app/src/main/java/com/example/wnews/LoginActivity.kt
> +        } else println("hola")
Hahaha it's always good to remember where you came from here

2022-10-04 14:48 UTC, merged